### ISSUE TITLE
Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed on login to SF

### ISSUE THREAD

**Issue by eklimanov** [forcedotcom/SalesforceMobileSDK-WindowsSamples#30]
Hello! I try run both SmartSyncExplorer and RestExplorer samples and I get next exception:

`Windows.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Salesforce.SDK.Pages.AccountPage.InitializeComponent()
   at Salesforce.SDK.Universal.Universal_XamlTypeInfo.XamlTypeInfoProvider.Activate_6_AccountPage()
   at Salesforce.SDK.Universal.Universal_XamlTypeInfo.XamlUserType.ActivateInstance()
   at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType)
`
How can I run these examples?

**Comment by helenren** [comment]
this issue is fixed on the latest build on unstable. Please have a try from there @eklimanov . Thanks.
